"""empty message

Revision ID: 59b09f5d5209
Revises: 7ab6d0dee2da
Create Date: 2023-04-03 13:47:51.777114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59b09f5d5209'
down_revision = '7ab6d0dee2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(), nullable=True))
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('roles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
