"""empty message

Revision ID: 996a26b59d43
Revises: 59b09f5d5209
Create Date: 2023-04-03 21:47:58.298432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996a26b59d43'
down_revision = '59b09f5d5209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
